apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-storage
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /dev/data
